version: 0.1

environment_variables:
  plaintext:


phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y curl wget

  pre_build:
    commands:

  build:
    commands:


  post_build:
    commands:
      - echo Build completed on `date +%F_%T`