version: 0.1

environment_variables:
  plaintext:
    -


phases:
  install:
    commands:
      -


  pre_build:
    commands:
      -

  build:
    commands:
      -


  post_build:
    commands:
      - echo Build completed on `date +%F_%T`