#!/bin/bash
ps -ef|grep manage.py|grep -v grep |awk '{print $2}' > /root/ca.log
#netstat -nplt |grep python3 |awk '{print $NF}' |awk -F '/' '{print $1}' | xargs

ps -ef|grep manage.py|grep -v grep |awk '{print $2}' |xargs -i kill -9 {} || true

rm -rf /root/django
echo "finished" >> /root/ca.log
my_path=$(dirname $0)
#pip3 install django
nohup python3 $my_path/manage.py runserver 0.0.0.0:8000  > /dev/null 2>&1 &