#!/bin/bash

ps -ef|grep manage.py|grep -v grep |awk '{print $2}' > /root/ca.log

ps -ef|grep manage.py|grep -v grep |awk '{print $2}' | xargs -i kill -9 {}

rm -rf /root/django

echo "finished" >> /root/ca.log
